name: "Publish Terraform Module"

on:
  push:
    branches:
      - main
    paths:
      - "src/modules/cc-vpc/**"

jobs:
  publish:
    name: "Publish VPC Module to JFrog"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://jfrogcfv.jfrog.io
        with:
          oidc-provider-name: github-jfrog
          oidc-audience: test

      - name: Publish module to JFrog
        working-directory: src/modules/cc-vpc
        run: |
          jf tf p \
            --namespace=jfrog \
            --provider=aws \
            --tag=${{ github.ref_name }}

    