name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::987213268383:role/aws-tf-gha-github-actions-role
          aws-region: ca-central-1

      # - name: Setup JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v4
      #   env:
      #     JF_URL: https://jfrogcfv.jfrog.io
      #   with:
      #     oidc-provider-name: github-jfrog
      #     oidc-audience: test

      # NOTE: S3 state bucket is owned by the ./src/bootstrap stack

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init -migrate-state

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve